version: 2

jobs:
  build:
    working_directory: ~/intergo
    docker:
      - image: circleci/golang:1.12.5
    steps:
      - checkout
      - run: go get
      - run: go test -v -race ./...
      - run: go test -bench .
      - run: go build .
